### ISSUE TITLE
This mod cause my game crash.

### ISSUE THREAD

**Issue by him126163** [P3pp3rF1y/SophisticatedBackpacks#516] opened 2022-07-01 01:43 UTC
When i install this mod and try to start the game,the game crash.

forge:40.1.52
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9024444/latest.log)

It's the latest verison of this mod.

**Comment by P3pp3rF1y** [comment] 2022-07-01 19:35
I don't see anything in that log pointing to sophisticated backpacks. The only thing I see in there is an exception caused by some mod that modifies ItemInHandRenderer and that's definitely not modified by sbp. So I will either need a crash log that shows that sbp is at fault or way to recreate without having to load the ton of mods you have there or you will need to complain to the mod that actually caused this crash.

**Comment by him126163** [comment] 2022-07-02 02:03
Maybe it's the reason of the optifine and krytpon,when i remove this two mods,the games can be load.

**Comment by P3pp3rF1y** [comment] 2022-07-12 20:45
closing as it's another mod causing the crash

**Closed as completed by P3pp3rF1y** 2022-07-12 20:45 UTC
Labels: question
