### ISSUE TITLE
Placing and Picking Up Backpack Causing Problems

### ISSUE THREAD

**Issue by djkommando** [P3pp3rF1y/SophisticatedBackpacks#937] opened 2023-12-28 01:48 UTC
**Describe the bug**
backpack has been working fine, until i placed it down on a hopper to empty into my Storage Drawer Controller and when i went to pick it back up my FOV zooms in slightly, my movement is really slow and i cannot access any of my inventory. also the backpack doesnt show up on my hot bar but i can right click and place it back down and everything is fine and i can access the backpack fine. this has happened to me once before (cant remember if it was on the hopper or not) and i believe i just updated the mod and i was fine. not sure if this something that would happen more often and i rarely take my primary backpack out of my inventory. before this instance i was able to pick up and place other backpacks while my primary one was in my inventory, but now with the error that is happening, i get the same result when picking up any of my backpacks. i also just noticed when taking screenshots that the info at the top of the screen shows blocks as unbreakable when i pick the backpack

**Screenshots**
placed backpack
![2023-12-27_20 36 15](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/155031126/50cd58b2-ff11-4005-b46c-b4fa8ff5310d)

backpack inventory
![2023-12-27_20 36 37](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/155031126/655f1333-acca-4f0c-8f7b-5c48cae5a090)

backpack picked up (in hand)
![2023-12-27_20 37 14](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/155031126/685ea6eb-6785-48b1-9a86-6540d50ed5b5)

**Versions**
1.19.2-3.19.4.977

**Comment by P3pp3rF1y** [comment] 2023-12-28 14:39
How are you picking up the backpack? Are you able to recreate that with just sophisticated somehow? Seems to me this is conflict with some mod or mods, but I have no idea what that might and at the same time I can't recreate so no idea how I could help you.

**Comment by djkommando** [comment] 2023-12-28 22:14
thanks for the quick reply!

its on the floor and i just shift right click as usual. but it first started when i had it on the hopper feeding the drawer controller. i just took a video and its now working correctly sometimes... if there's nothing you can think of, i guess ill just mess with it until it works correctly and never put it down again, which i rarely do anyway.
Minecraft 1 19 2 Singleplayer 2023 12 28 16 58 04


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Minecraft 1 19 2 Singleplayer 2023 12 28 16 58 04


 |

 |

 |



    On Thursday, December 28, 2023 at 09:39:36 AM EST, P3pp3rF1y ***@***.***> wrote:  
 
 


How are you picking up the backpack? Are you able to recreate that with just sophisticated somehow? Seems to me this is conflict with some mod or mods, but I have no idea what that might and at the same time I can't recreate so no idea how I could help you.

**Comment by P3pp3rF1y** [comment] 2023-12-29 00:02
I just retested in 1.19.2 on a hopper pulling out and I am unable to recreate so I will definitely need more info on how to recreate.

**Comment by djkommando** [comment] 2023-12-31 21:44
i just setup a storage system with hopper in a new world to try and recreate the issue from the start and when testing the backpack before placing it on the hopper is was already broken... one thing i noticed, but didnt really click until now, is that when i place it, sometimes it places sideways and that seems to be when i have the issue upon picking it up. the backpack is also brand from creative menu.
Minecraft 1 19 2 Singleplayer 2023 12 31 16 32 24


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Minecraft 1 19 2 Singleplayer 2023 12 31 16 32 24


 |

 |

 |


also here is a list of the mods i am using in case it is helpful.



    On Thursday, December 28, 2023 at 07:02:53 PM EST, P3pp3rF1y ***@***.***> wrote:  
 
 


I just retested in 1.19.2 on a hopper pulling out and I am unable to recreate so I will definitely need more info on how to recreate.

**Comment by P3pp3rF1y** [comment] 2024-01-01 16:33
Well again I am unable to recreate. Are you tecreating this with just SB? Are you in single player or on a server?

**Comment by P3pp3rF1y** [comment] 2024-01-01 16:35
Actually I see that it is in singleplayer so nevermind that question. In that case it's caused by one of the other mods in your pack

**Comment by P3pp3rF1y** [comment] 2024-01-01 16:43
Also you seem to suggest in one of the previous messages that you wanted to include mod list but I don't see it anywhere in the issue. Best to include as link to pastebin or similar service

**Comment by djkommando** [comment] 2024-01-01 19:24
i did insert it in the last email as a picture but i guess it didnt work... here it is as an attachment.
    On Monday, January 1, 2024 at 11:43:33 AM EST, P3pp3rF1y ***@***.***> wrote:  
 
 


Also you seem to suggest in one of the previous messages that you wanted to include mod list but I don't see it anywhere in the issue. Best to include as link to pastebin or similar service

**Comment by P3pp3rF1y** [comment] 2024-01-02 15:50
> i did insert it in the last email as a picture but i guess it didnt work... here it is as an attachment. On Monday, January 1, 2024 at 11:43:33 AM EST, P3pp3rF1y ***@***.***> wrote: Also you seem to suggest in one of the previous messages that you wanted to include mod list but I don't see it anywhere in the issue. Best to include as link to pastebin or similar service — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

You are probably replying to email instead of replying in github and that doesn't seem to transfer attachment to github so I still can't see anything.

**Comment by P3pp3rF1y** [comment] 2024-01-02 15:52
Actually I can see that you are with the email icon so it seems you need to go to github to attach properly

**Comment by djkommando** [comment] 2024-01-02 20:50
can you see it now?

![Screenshot 2023-12-31 164337](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/155031126/389ce1f7-37c9-480a-b5c5-66c51a9e4230)

**Comment by P3pp3rF1y** [comment] 2024-09-18 20:09
I am guessing back then it was some interaction with carry on mod, but other modpacks still run carry on with SB these days and that seems to work well so I am closing this given no other reports

**Closed as completed by P3pp3rF1y** 2024-09-18 20:09 UTC
Labels: Need Info
