### ISSUE TITLE
Game crash (server connection) after inserting items into backpack

### ISSUE THREAD

**Issue by germansquid** [P3pp3rF1y/SophisticatedBackpacks#902] opened 2023-11-14 18:41 UTC
**Describe the bug**
Crash occures everytime when i try to add items into the packpack via the right-click option. Server connection ends instantly showing an 'out of bounce-error (Screenshot following). Occurance is on a serrver hosted by me. Same mod-configuration and other installed mods like in my forge-offline Build. There is everything working just fine. Server is running `1.19.2 (43.2.0)` with Forge.

Note: When placing the backpack on the ground and opening it or just having it in taskbar allows for "regular usage" with drag and drop items into it after opening the backpack inventory. Error accures only if items are to be fed to the backpack via right-click operation while `+` icon shown on backpack. 

**To Reproduce**
1. Have backpack in inventory.
2. Click on any item (not backpack) 
3. Right-click drop it into the backpack (alt.: click backpack and right-click any items)

**Expected behavior**
Items should just be dumped into storage. 

**Screenshots**
![2023-11-14 19_37_14-Minecraft_ 1 19 2](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/57751169/ba91f773-7647-496e-aaaf-2b2b6722c86c)

**Versions**
CLIENT: Minecraft 1.19.2 w. Forge `(43.2.0)`
SERVER: Minecraft 1.19.2 w. Forge `(43.3.0)`
![2023-11-14 19_40_05-Dateien _ Aternos _ Kostenlose Minecraft Server - Persönlich – Microsoft​ Edge](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/57751169/abe1a0b8-c19d-4ce6-babb-c13d40600964)

Full log file: 
[crash-2023-11-13_14.29.39-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13354280/crash-2023-11-13_14.29.39-fml.txt)

**Comment by germansquid** [comment] 2023-11-14 18:56
Update: Tried around abit. 
Picking up backpack with right-click also results in instantly crashing. If i install the magnet and use the pickup function to automaticly transport items into the backback **this works**. So it really is just this one function with item insertion. "Everything" else works as expected.

**Comment by P3pp3rF1y** [comment] 2023-11-14 20:14
The crash you have shared is for FTB ultimine missing its dependency so I will need the actual crash that happened for you. 

But I also am unable to recreate when using the backpack on item to right click that in or the other way around so this is likely caused by something else in your modpack interacting here. Are you able to recreate with just sophisticated mods?

**Comment by DragoHanter** [comment] 2023-11-14 23:35
So I was going to tweek my inventory and redo the sorting of a bag and when I click the settings button the entire game crashes with this exact message. 
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/9768945/ae0a573a-e694-4b66-a794-0908ffb0ea32)
Seems to work in single player but on my friends server its a crash fest on bmc4 v21.

**Comment by P3pp3rF1y** [comment] 2024-09-18 21:12
closing given no follow up

**Closed as completed by P3pp3rF1y** 2024-09-18 21:12 UTC
Labels: Need Info
