### ISSUE TITLE
Game crashed  by using the tank upgrade

### ISSUE THREAD

**Issue by zoer0605** [P3pp3rF1y/SophisticatedBackpacks#670] opened 2022-12-22 11:25 UTC
**Describe the bug**
In the 1.19.2 version my game keeps crashing since I put a lava bucket in the bucket slot in the diamond Backpack with tank upgrade.

**To Reproduce**
1. Open diamond backpack with tank upgrade
2. Put lava bucket in the bucket slot
4. Game crashed and you cant open the file again
5. See error "Exit code -1"

**Expected behavior**
That the lava goes in the tank without crashing. (It doesn't happen when you put the lava direct in the tank)

**Versions**
Mod version 1.19.2-3.18.35.751
Forge version 1.19.2

**Comment by P3pp3rF1y** [comment] 2022-12-22 20:27
Are you using optifine - if so there's what crashes you. Just stop using it and bug is gone.

**Comment by P3pp3rF1y** [comment] 2023-01-10 15:38
I have seen this issue caused by optifine and nothing else so far so I am closing as there was no additional info provided either.

**Closed as completed by P3pp3rF1y** 2023-01-10 15:38 UTC
