### ISSUE TITLE
Experience pump do not fix elytra in curio slot

### ISSUE THREAD

**Issue by willis1030** [P3pp3rF1y/SophisticatedBackpacks#535] opened 2022-07-16 03:48 UTC
the elytra is already enchanted with mending, but not fixed with experience from experience pump.
curios-forge, caelus-forge, curiouselytra-forge is installed.
1.16.5 and 1.18.2 are the same situation.

**Comment by P3pp3rF1y** [comment] 2022-07-19 21:17
This is a duplicate of #411 feature that I am planning to add, but one ticket is enough

**Closed as completed by P3pp3rF1y** 2022-07-19 21:17 UTC
