### ISSUE TITLE
(Feature Request) Etched mod Compatibility

### ISSUE THREAD

**Issue by ErikolGamer14** [P3pp3rF1y/SophisticatedBackpacks#1048] opened 2024-04-30 18:23 UTC
Etched custom music discs are unable to be played on the Jukebox upgrade
Will be cool if compatibility is added.

**Comment by P3pp3rF1y** [comment] 2024-05-02 05:32
Duplicate of #1010

**Closed as completed by P3pp3rF1y** 2024-05-02 05:32 UTC
