### ISSUE TITLE
Crash when trying to take item from backpack

### ISSUE THREAD

**Issue by Rimplestilt** [P3pp3rF1y/SophisticatedBackpacks#884] opened 2023-10-22 20:37 UTC
1.20.1 Forge with the latest Sophisticated backbacks mod.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000028ed3d539a8, pid=9376, tid=6408
#
# JRE version: Java(TM) SE Runtime Environment (17.0.8+9) (build 17.0.8+9-LTS-211)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.8+9-LTS-211, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# J 46385 c2 net.p3pp3rf1y.sophisticatedbackpacks.client.init.ModItemColors.lambda$registerItemColorHandlers$1(Lnet/minecraft/world/item/ItemStack;I)I sophisticatedbackpacks@3.18.65.935 (48 bytes) @ 0x0000028ed3d539a8 [0x0000028ed3d52dc0+0x0000000000000be8]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\fugfu\Desktop\PolyMC-Windows-Portable-5.1\instances\LiminalCraft\minecraft\hs_err_pid9376.log
Compiled method (c2) 12357327 46385       4       net.p3pp3rf1y.sophisticatedbackpacks.client.init.ModItemColors::lambda$registerItemColorHandlers$1 (48 bytes)
 total in heap  [0x0000028ed3d52a90,0x0000028ed3d55b28] = 12440
 relocation     [0x0000028ed3d52be8,0x0000028ed3d52dc0] = 472
 main code      [0x0000028ed3d52dc0,0x0000028ed3d54860] = 6816
 stub code      [0x0000028ed3d54860,0x0000028ed3d54910] = 176
 oops           [0x0000028ed3d54910,0x0000028ed3d54958] = 72
 metadata       [0x0000028ed3d54958,0x0000028ed3d54b28] = 464
 scopes data    [0x0000028ed3d54b28,0x0000028ed3d55378] = 2128
 scopes pcs     [0x0000028ed3d55378,0x0000028ed3d557f8] = 1152
 dependencies   [0x0000028ed3d557f8,0x0000028ed3d55848] = 80
 handler table  [0x0000028ed3d55848,0x0000028ed3d55aa0] = 600
 nul chk table  [0x0000028ed3d55aa0,0x0000028ed3d55b28] = 136
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Process exited with code 1.

**Comment by P3pp3rF1y** [comment] 2023-10-23 05:32
could you add the actual crash log from `crash-reports` folder? I cant do anything with the info that was provided here.

**Comment by TeslaReloaded** [comment] 2023-10-24 11:54
I have the same issue - the game crashes whenever I try to take something out of the backpack. Most of the times the game just freezes without creating the crash log, but I've managed to get the log once:

[crash-2023-10-24_14.53.22-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13114139/crash-2023-10-24_14.53.22-client.txt)

**Comment by Rimplestilt** [comment] 2023-10-24 18:18
This was the actual crash log section from the report...
But the .txt file formatted weird when i pasted it into github, sorry about that, it showed normally until i posted the issue. If i can find the crash link again, i will send it (but it is just the entire text of this github issue)

**Comment by P3pp3rF1y** [comment] 2023-10-24 21:42
> I have the same issue - the game crashes whenever I try to take something out of the backpack. Most of the times the game just freezes without creating the crash log, but I've managed to get the log once:
> 
> 
> 
> [crash-2023-10-24_14.53.22-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13114139/crash-2023-10-24_14.53.22-client.txt)
> 
> 

This is caused by core version that is more recent than backpacks one. Just update backpacks as well and you're good

**Comment by TeslaReloaded** [comment] 2023-10-24 21:52
> > I have the same issue - the game crashes whenever I try to take something out of the backpack. Most of the times the game just freezes without creating the crash log, but I've managed to get the log once:
> > [crash-2023-10-24_14.53.22-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13114139/crash-2023-10-24_14.53.22-client.txt)
> 
> This is caused by core version that is more recent than backpacks one. Just update backpacks as well and you're good

Thank you! Although turned out I had the backpack mod of the latest version (1.20.1-3.18.65.935) and outdated core mod (1.20.1-0.5.83.395).

**Comment by P3pp3rF1y** [comment] 2023-11-14 20:28
looks like that version of core had a broken version with `1.20.1` included at the start which caused SB then incorrectly assuming that's high enough core version. Later versions of core are good so I am closing this now.

**Closed as completed by P3pp3rF1y** 2023-11-14 20:28 UTC
Labels: Need Info
