### ISSUE TITLE
inventory in inception bags keep deleting

### ISSUE THREAD

**Issue by OddJarro** [P3pp3rF1y/SophisticatedBackpacks#410] opened 2022-01-30 08:42 UTC
I have 4 backpacks within my main backpack. Randomly when I have a backpack with inventory, the backpack to the furthest left will delete the inventory within it. I have lost hours of inventory twice now and it only has happened to the leftmost backpack both times.

**Comment by P3pp3rF1y** [comment] 2022-01-30 22:34
I am pretty sure that what's happening is that you have two backpacks in the world with the same UUID as there's no difference where in inventory backpack is in terms of its inventory - all of the backpacks have their inventory stored separately and linked to their UUID (which can be seen in advanced tooltip - F3 + h). 
But it there are two backpacks with the same UUID (the backpack was duplicated in creative / given using some mod as starting gear already with UUID) you will see inventory randomly disappearing or getting additional items because the two backpacks will both try to store their inventory in that common storage and when their cached contents need to be restored it uses the storage and at that point these odd changes happen.

So you will need to find out backpacks that use the same UUID and just use one of them. 

Or if this is not the case, I will need more precise steps on how to reproduce as this is not it - I am testing inception regularly and have never seen anything like this and haven't changed inception or how inventory is stored in a very long while.

**Comment by OddJarro** [comment] 2022-01-30 23:09
All my backpacks have different uuid's.
I can share my mod list.
I am not sure really how to reproduce what is happening. The first time it happened, I died and when I went to get my stuff, the leftmost backpack deleted its inventory. The second time it happened I disconnected from the server to take a break, then when I came back, the leftmost backpack again deleted it's inventory.

**Comment by OddJarro** [comment] 2022-01-30 23:20
mod list
https://imgur.com/PPDBkEc

**Comment by P3pp3rF1y** [comment] 2022-01-31 06:07
And are you playing on server or in single player? the uuid could be the same between your backpack and another player's backpack or it could be the same with a backpack that you're using separately somewhere.

**Comment by P3pp3rF1y** [comment] 2022-02-13 21:11
any additional info on this?

**Comment by P3pp3rF1y** [comment] 2022-03-10 17:19
closing given there was no additional info provided. very likely not something that easily happen again give this is the only report of the issue

**Closed as completed by P3pp3rF1y** 2022-03-10 17:19 UTC
Labels: Need Info
