### ISSUE TITLE
Backpack in Curio slot shows bugged inventory when accessed through hotkey

### ISSUE THREAD

**Issue by MaxWasUnavailable** [P3pp3rF1y/SophisticatedBackpacks#480] opened 2022-05-23 18:10 UTC
**Describe the bug**
I upgraded a backpack to diamond tier, added the highest tier stacking upgrade as well as crafting and furnace upgrades.

At first, it worked fine in the curios slot. But after logging out and in to the server and playing for a bit, the UI for the backpack (when accessed as curio, using the hotkey) was messed up and caused weird (temporary) inventory glitches.

The inventory is only 2 rows tall, and far less long. It also does not display upgrades anymore.

When I take it out of my curio slot, I can access it as normal both via hotkey or right click.

**To Reproduce**
1. Have backpack in curios slot.
2. Use keybind to access backpack.

**Expected behavior**
Backpack works properly while equipped as a curio.

**Screenshots**
TODO.
I will grab one next play session.

**Versions**
Forge: 40.1.22
Sophisticated Backpacks: 1.18.2-3.16.4.584
Sophisticated Core: 1.18.2-0.1.0.19

**Error Log**
```
[19:49:27] [Render thread/ERROR]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index 108 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.m_38853_(StorageContainerMenuBase.java:1307) ~[sophisticatedcore-1.18.2-0.1.0.19.jar%23268!/:1.18.2-0.1.0.19]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_182406_(AbstractContainerMenu.java:568) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.p3pp3rf1y.sophisticatedcore.network.SyncSlotStackMessage.handleMessage(SyncSlotStackMessage.java:48) ~[sophisticatedcore-1.18.2-0.1.0.19.jar%23268!/:1.18.2-0.1.0.19]
	at net.p3pp3rf1y.sophisticatedcore.network.SyncSlotStackMessage.lambda$onMessage$0(SyncSlotStackMessage.java:39) ~[sophisticatedcore-1.18.2-0.1.0.19.jar%23268!/:1.18.2-0.1.0.19]
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:208) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.p3pp3rf1y.sophisticatedcore.network.SyncSlotStackMessage.onMessage(SyncSlotStackMessage.java:39) ~[sophisticatedcore-1.18.2-0.1.0.19.jar%23268!/:1.18.2-0.1.0.19]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:68) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:75) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:75) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7413_(ClientPacketListener.java:1824) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1013) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.22.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**Comment by MaxWasUnavailable** [comment] 2022-05-24 18:53
Update with example image:
![javaw_X4Y6RQ547g](https://user-images.githubusercontent.com/89798523/170111123-d0dc0964-5646-43e4-b80c-96f67886ebeb.png)

**Comment by Charmanth** [comment] 2022-05-24 22:15
I'm having this issue myself.  Was working fine on my server yesterday, only change was minecolonies update.  Only affecting me?  The one other person on the server with a diamond backpack has not yet had this issue

**Comment by Charmanth** [comment] 2022-05-24 22:50
Restarting the client seems to have fixed it, at least temporarily

**Comment by MaxWasUnavailable** [comment] 2022-05-25 00:46
A client restart appears to not fix it. A server restart temporarily fixes it sometimes until it happens again. (On a dedicated server)

**Comment by P3pp3rF1y** [comment] 2022-05-25 10:00
would you be able to get me logs from your client `debug.log` and try to find entries in there that contain something like `Error getting backpack wrapper`?

**Comment by MaxWasUnavailable** [comment] 2022-05-25 10:40
I do not appear to have a debug.log. How would I go about enabling that?

**Comment by MaxWasUnavailable** [comment] 2022-05-25 10:50
In the latest.log I found the following:

```
Error getting backpack wrapper - Unable to find inventory handler for "curios_back"
```

Attached is the full log since it's a tad too large for pastebin:
[2022-05-23-6.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8770386/2022-05-23-6.log)

**Comment by P3pp3rF1y** [comment] 2022-05-26 18:31
Looks like enigmatic legacy crashes when tags update event happens very likely causing SBP logic (which uses the same event to update its curios compat on client) to not work. Please try without that mod or without that issue happening and let me know if that helps.

```
[19:14:15] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "com.integral.enigmaticlegacy.objects.TransientPlayerData.getPlayer()" because "msg.playerData" is null
	at com.integral.enigmaticlegacy.packets.clients.PacketSyncTransientData.lambda$handle$0(PacketSyncTransientData.java:33) ~[EnigmaticLegacy-2.21.1.jar%23144!/:2.21.1]
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:208) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at com.integral.enigmaticlegacy.packets.clients.PacketSyncTransientData.handle(PacketSyncTransientData.java:28) ~[EnigmaticLegacy-2.21.1.jar%23144!/:2.21.1]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:68) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:75) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:75) ~[forge-1.18.2-40.1.22-universal.jar%23317!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7413_(ClientPacketListener.java:1824) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at jeresources.util.LootTableHelper.getLootTables(LootTableHelper.java:187) ~[JustEnoughResources-1.18.2-0.14.1.167.jar%23191!/:0.14.1.167]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:42) ~[JustEnoughResources-1.18.2-0.14.1.167.jar%23191!/:0.14.1.167]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:34) ~[JustEnoughResources-1.18.2-0.14.1.167.jar%23191!/:0.14.1.167]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) ~[JustEnoughResources-1.18.2-0.14.1.167.jar%23191!/:0.14.1.167]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-1.18.2-0.14.1.167.jar%23191!/:0.14.1.167]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:91) ~[JustEnoughResources-1.18.2-0.14.1.167.jar%23191!/:0.14.1.167]
	at mezz.jei.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:133) ~[jei-1.18.2-9.7.0.195.jar%23188!/:9.7.0.195]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) ~[jei-1.18.2-9.7.0.195.jar%23188!/:9.7.0.195]
	at mezz.jei.load.PluginLoader.createRecipeCategories(PluginLoader.java:133) ~[jei-1.18.2-9.7.0.195.jar%23188!/:9.7.0.195]
	at mezz.jei.load.PluginLoader.createRecipeManager(PluginLoader.java:159) ~[jei-1.18.2-9.7.0.195.jar%23188!/:9.7.0.195]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:129) ~[jei-1.18.2-9.7.0.195.jar%23188!/:9.7.0.195]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:112) ~[jei-1.18.2-9.7.0.195.jar%23188!/:9.7.0.195]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:143) ~[jei-1.18.2-9.7.0.195.jar%23188!/:9.7.0.195]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:106) ~[jei-1.18.2-9.7.0.195.jar%23188!/:9.7.0.195]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1270) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1013) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.22.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**Comment by MaxWasUnavailable** [comment] 2022-05-26 22:41
We use this in our server modpack; So we can't really remove that mod without it breaking a large portion of the world / what we've got going on.

Would there be any way you can detect this / catch this and prevent SBP from breaking? Completely understandable if not, considering it seems to be another mod that's at fault.

**Comment by TinyPandas** [comment] 2022-05-27 03:22
+1 this issue on ATM6 Modpack does not contain enigmatic legacy

Issue was non-existent prior to a server restart. My log file does contain `"[19:26:51] [main/ERROR]: Error getting backpack wrapper - Unable to find inventory handler for "curios_back"`

_apologies for not posting the debug log, curseforge has it disabled by default and client restart fixed the issue_
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8783718/latest.log)

Everything I find in the log points to [this line](https://github.com/P3pp3rF1y/SophisticatedBackpacks/blob/3c083bf293a68e48f32f8d6e6368793515e2e6d3/src/main/java/net/p3pp3rf1y/sophisticatedbackpacks/common/gui/BackpackContainer.java#L1006).

**Comment by P3pp3rF1y** [comment] 2022-05-28 14:22
@TinyPandas the issue in ATM6 is likely somewhat different. Basically while investigating this the only cause I have found was that at the time the backpack is first opened/rendered/some upgrade runs in it the curios tags are not synced to client properly and thus client doesn't know that backpack can go in curios slot and curios implementation initializes without the understanding of tagged slots. So in 1.18.2 I have added a fix for this which runs when tags get synced to client and reinitializes the curios implementation. That reaction to tags sync is very likely broken by the issue I pointed to above and thus at that point it relies only on the 1.16 logic which may break sometimes and requires client reload to fix itself.

**Comment by Odey555** [comment] 2022-05-29 23:00
> +1 this issue on ATM6 Modpack does not contain enigmatic legacy
> 
> Issue was non-existent prior to a server restart. My log file does contain `"[19:26:51] [main/ERROR]: Error getting backpack wrapper - Unable to find inventory handler for "curios_back"`
> 
> _apologies for not posting the debug log, curseforge has it disabled by default and client restart fixed the issue_ [latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8783718/latest.log)
> 
> Everything I find in the log points to [this line](https://github.com/P3pp3rF1y/SophisticatedBackpacks/blob/3c083bf293a68e48f32f8d6e6368793515e2e6d3/src/main/java/net/p3pp3rf1y/sophisticatedbackpacks/common/gui/BackpackContainer.java#L1006).

I'm on ATM7 and I can confirm that restarting the client fixed it. 
The bug only happened once though so no idea what could've caused it

**Comment by P3pp3rF1y** [comment] 2022-06-11 07:28
In the latest release on curseforge there's a changed implementation of how curios tags are checked - instead of checking jut the first time curios compat is needed or when the tags get synchronized to client which can be broken by other mods the new logic regularly tries to get the curios tags and caches them for a little bit. So that should fix the issue and in the worst case if it happens it should go away after a few seconds.

**Closed as completed by P3pp3rF1y** 2022-06-11 07:28 UTC
Labels: Need Info

**Comment by BBowdon00** [comment] 2022-06-17 20:45
[17Jun2022 15:52:17.065] [Render thread/ERROR] [sophisticatedbackpacks/]: Error getting backpack wrapper - Unable to find inventory handler for "curios_back"
[17Jun2022 15:52:17.081] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
	at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
	at java.util.ArrayList.get(Unknown Source) ~[?:?]
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.m_38853_(StorageContainerMenuBase.java:1279) ~[sophisticatedcore-1.18.2-0.2.8.35.jar%23270!/:1.18.2-0.2.8.35]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_182410_(AbstractContainerMenu.java:574) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.m_182410_(StorageContainerMenuBase.java:295) ~[sophisticatedcore-1.18.2-0.2.8.35.jar%23270!/:1.18.2-0.2.8.35]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_6837_(ClientPacketListener.java:985) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket.m_5797_(ClientboundContainerSetContentPacket.java:44) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket.m_5797_(ClientboundContainerSetContentPacket.java:11) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1013) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23310!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.47.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
