### ISSUE TITLE
Sophisticated Backpacks On the ground Collapse

### ISSUE THREAD

**Issue by fzrdwa123456** [P3pp3rF1y/SophisticatedBackpacks#777] opened 2023-05-28 01:39 UTC
**Describe the bug**
Sophisticated Backpacks On the ground Collapse

Crash log if it's a crash.
[crash-2023-05-28_09.25.24-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11583411/crash-2023-05-28_09.25.24-client.txt)

Info on what other mods you're using that may cause a conflict here if applicable.
And ModernFix mod conflict

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Click on '....' tab
3. Do something

**Expected behavior**

**Screenshots**

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
Sophisticated Backpacks-1.18.2-3.18.48.835
Sophisticatedcore-1.18.2-0.5.56.273
Forge-40.2.2

**Comment by fzrdwa123456** [comment] 2023-05-28 01:39
I hope you can fix it

**Comment by fzrdwa123456** [comment] 2023-05-28 01:40
My English is not very good because I use a translator

**Comment by P3pp3rF1y** [comment] 2023-05-28 11:54
this is a duplicate of #775  so closing

**Closed as completed by P3pp3rF1y** 2023-05-28 11:54 UTC
