### ISSUE TITLE
Food Duplication With Bowl-Made Items

### ISSUE THREAD

**Issue by NutNibbler** [P3pp3rF1y/SophisticatedBackpacks#237] opened 2021-09-05 01:37 UTC
**Describe the bug**
Food can be duplicated indefinitely with any backpack with any upgraded variant of the Auto-Feeding upgrade as well as the Stack Limit Upgrade.
There are mods that add many Soups and other food items that require a Bowl(and return it upon consumption), however the Mushroom Soup from Vanilla works with this bug too.

**To Reproduce**
1. Utilize any backpack upgraded with an Auto-Feed upgrade and Stack Upgrade
2. Insert a food item that is made with a Bowl(and that will return the bowl when eaten), the quantity must be over the natural stack limit.
3. Let the Auto-Feed upgrade do it's job(feed you).
4. An additional full stack of the food product will appear inside the backpack every time the backpack feeds the player.

**Expected behavior**
Food would be consumed and item quantity would drop accordingly.

**Screenshots**

**Versions**
Forge: 36.2.2
Mod: 3.2.7.326
Modpack: Better Minecraft For 1.16 Forge
Link to modpack: [https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack](url)

**Comment by P3pp3rF1y** [comment] 2021-09-07 21:17
So mushroom soup by itself in vanilla doesn't have this issue. It's an issue of another mod modifying how it works. 
Could you help narrow down which one it is in the modpack?

I am guessing that in your case you are inserting a stack of more than one mushroom soup so it would be a mod that actually allows mushroom soups to stack or another mod that modifies result of what's remaining after these are eaten.

In the past there was an issue with charm but that one was fixed and I have just retested that sophisticated backpacks with charm modified mushroom stews work as expected.

**Comment by NutNibbler** [comment] 2021-09-08 00:10
Let me do more direct tests under my situation and Ill get back.

**Comment by NutNibbler** [comment] 2021-09-08 01:22
Im currently occupied but I know that it works on foods from the Farmer's Delight mod(v0.4.6).

**Comment by P3pp3rF1y** [comment] 2021-09-10 16:02
I have just tested with Farmer's Delight Bowl of Stuffed Pumpkin and it also works correctly

**Comment by mmarquezs** [comment] 2021-09-11 15:20
I had the same issues with the pack Medieval Minecraft version 27.5 in my server. (Which is from the same people of the other pack).
With the Mushroom stew duplicating in my case example.
It took quite a while to reproduce and find which mods cause it.... but I got it just now after a couple of hours (I was hoping less time :( ).
You need, apart from your mod, this two others:
- Farmers Delight ( FarmersDelight-1.16.5-0.4.6.jar )
- Charm ( charm-forge-1.16.5-2.3.2.jar )
Default generated config settings in both. (not using the configs from the pack just the auto generated ones)

For testing just needed the backpack + the feeding upgrade and a stack of stew in the bag.  And once you get hungry it will trigger the duplication. 

If you only use one of the mods with the backpack then 0 issues, you need both to trigger this. No idea why.
No idea if it's something you can fix, something one of them should fix, both, all or what happens.
Since it happens when using your mod, as eating normally doesn't seem to trigger it I guess it makes sense that you try to see whats going on.
At the end maybe is not your fault and then we can blame one of the other or both or whatever to see if they can fix it somehow.  But at this point no idea. 
Or... it could stay as it is and simply not mix two mods which modify the stacking of bowls.... as for now disabling the stacking in Farmersdeligh (enableStackableSoupItems = false) seems to fix the issue and then since there is Charm the stacking still works,  @NutNibbler if you wanted a fix for now this is it. Unless in that pack is triggered by other mods.

**Comment by NutNibbler** [comment] 2021-09-16 01:48
The modpack running on my server does have Charm as well. I apologize for almost no feedback but I've been working out of state the past week and didn't set up remote access to my server. Also don't have access to the Minecraft application right now. 

Hoping to be able to get better details in 4 days but it could be longer, sorry.

@mmarquezs I appreciate you bringing this information forward since I currently can't.

**Comment by P3pp3rF1y** [comment] 2021-09-19 13:41
I have debugged this and it's an issue of both of the mods providing stackable stews functionality with each going about that in different way where charm always expects that only empty bowl is returned as a result of eating and actually farmer's delight overrides this to only return empty bowl when eating the last mushroom stew and in all the other cases return decreased count (it adds empty bowl to player's inventory separately). 
The only reason that this doesn't break when eating by hand is that when Charm adds the resulting stack into player's inventory it ignores result of this addition which is that only a few mushroom stews were added and the rest couldn't be added to player's hand and then the rest of its logic kicks in which again decreases the number of stews in player's hand to correct value. And in this case Charm actually doesn't even add the empty bowl to player's inventory but because it was added by Farmer's delight it seems to work correctly. 

The problem with this is that with feeding upgrade player actually doesn't have the food in hand and thus adding the result of eating in Charm will add the reduced mushroom stew stack result from Farmer's delight into player's inventory and then Charm only reduces its stack in the backpack. I can't see any way to work around this on my side.

So the fix for this is to disable stacking of stews in one of these mods so that only one logic can kick in.

**Closed as completed by P3pp3rF1y** 2021-09-19 13:41 UTC
Labels: Need Info
