### ISSUE TITLE
XP In Tank Upgrade Not Displaying Properly

### ISSUE THREAD

**Issue by mistersquidface** [P3pp3rF1y/SophisticatedBackpacks#1165] opened 2024-09-28 21:37 UTC
I attached the XP Pump Upgrade and Tank Upgrade to my backpack and when XP goes into the tank, instead of displaying the normal green XP bubbles inside the tank's capacity meter on the side, it just displays glitched, random, multicolored pixels. The meter still works, but the texture is glitched. I'm using the mods in a modpack I assembled myself, but I don't think there are any conflicts besides Chipped maybe, since I've heard other people have problems with Chipped and Sophisticated Backpacks before.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open the backpack
2. Attach the XP Pump Upgrade
3. Attach the Tank Upgrade
4. Set the pump to pull XP from the player

**Expected behavior**
What should happen is the meter fills with a green texture that looks like XP bubbles, but the texture doesn't render properly

**Screenshots**
![image](https://github.com/user-attachments/assets/2f585971-06df-4370-8adb-bcfe1e98507b)

**Versions**
I am using version 3.20.10.1109 of Sophisticated Backpacks, version 0.6.30.701 of Sophisticated Core, and Forge version 47.3.10

**Comment by P3pp3rF1y** [comment] 2024-09-29 11:07
Shows correctly for me. Are you able to recreate with just SB / core?

**Comment by mistersquidface** [comment] 2024-09-29 15:49
> Shows correctly for me. Are you able to recreate with just SB / core?

I tried it with just the base mod and core and it works fine, so it's probably a compatibility issue.

**Comment by P3pp3rF1y** [comment] 2024-09-29 21:27
If you can figure out what mod addition breaks it that would be good, I can check if I am potentially doing something here that makes this incompatible with something that mod is doing.

**Comment by Skarly75** [comment] 2024-09-30 20:31
I have the same issue, and figured out what mod is, in my case its:
Minecraft ver 1.20.1
 Refurbished Furniture 1.0.6
Im ussing:
SB 3.20.10.1109
SC 0.6.30.701
Forge 47.3.5

Btw im not sure if it have the same issue in sophisticated storage cus dont have the tank upgrade to see how it works

**Comment by mistersquidface** [comment] 2024-09-30 21:56
I'm not sure what mod I have that's causing the issue, since I'm not using Refurbished furniture, but I'll still try to figure it out. If you have any ideas for what kind of mod it might be, let me know. I'll see what I can find in the meantime.

**Comment by mistersquidface** [comment] 2024-09-30 22:30
I figured it out: Chipped is the problem. I disabled Chipped and it's API, Athena, and that worked. Hopefully this gives you enough information.

**Comment by Skarly75** [comment] 2024-09-30 23:30
> I'm not sure what mod I have that's causing the issue, since I'm not using Refurbished furniture, but I'll still try to figure it out. If you have any ideas for what kind of mod it might be, let me know. I'll see what I can find in the meantime.

that make sence to me because in my case only have the horizontal lines but with the aspect of your vertical, so isnt the same bug but same issue i think

**Comment by P3pp3rF1y** [comment] 2024-11-03 18:28
I only got to this now and tried with the versions of chipped / resourcefullib / athena that were the most recent at the time of your last feedback and I am still not able to recreate so it's something else that's doing it for you and I will need more info if it's still happening.

**Comment by Cuetsu** [comment] 2024-11-10 19:38
I have the same issue and it happens when I add Stellarity with Sophisticated Backpacks (don't have any other mods added).
Minecraft version: 1.20.1
Forge - 47.3.6
Stellarity-v2-0e
Sophisticated Backpacks-1.20.1-3.20.12.1126
Sophisticated Core-1.20.1-0.6.36.741

**Comment by P3pp3rF1y** [comment] 2024-11-11 07:50
> I have the same issue and it happens when I add Stellarity with Sophisticated Backpacks (don't have any other mods added). Minecraft version: 1.20.1 Forge - 47.3.6 Stellarity-v2-0e Sophisticated Backpacks-1.20.1-3.20.12.1126 Sophisticated Core-1.20.1-0.6.36.741

Thanks for this, based on that I was able to recreate and adjusted the rendering to be close to what vanilla does and now the issue is fixed in the latest Sophisticated Core release on curseforge

**Closed as completed by P3pp3rF1y** 2024-11-11 07:50 UTC
Labels: question
