### ISSUE TITLE
Sophisticated Backpacks causing NBT data error Even when Empty

### ISSUE THREAD

**Issue by Zelioth** [P3pp3rF1y/SophisticatedBackpacks#619] opened 2022-10-04 17:12 UTC
**Describe the bug**
A player began to get disconnected from an error "Internal Exception: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 209710bytes where maxed allowed: 2097152" This error was caused by her trying to open her Netherite Backpack. We managed to place the pack but every time we looked at it we would crash. I assume that is because it was acting as a chest and loading the inventory when we looked at it. I managed to put a pipe and chest to it and pipe out all the items thinking it would fix it. It did not. So we managed to break the pack and clear floating entity items and it deleted the pack entirely. The pack was confirmed to be empty besides upgrades that were applied to the pack. 

Auto-smelting - gold
Advanced magnet - gold
Stack upgrade tier 3
Advanced pickup -gold 

Crafting upgrade 
2nd Stack upgrade tier 3

**To Reproduce**
1. Create and use a Netherite Pack. (Seems to be the only one with the issue so far. I have only had one player report this issue)
2. Adding upgrades and items eventually caused it to create a NBT tag that was too large for MC to allow 
3. Crashed clients without any log or debug info only screen error stating the error. 

**Expected behavior**
Packs should not create NBT data that is over the allowed limit of Minecraft server to client connection. 

**Screenshots**

**Versions**
Minecraft : 1.19.2
Forge : 43.1.27
SBP : 3.18.29.719
SC: 0.5.12.130

**Comment by P3pp3rF1y** [comment] 2022-11-30 09:13
this is caused by an item with an excessively large nbt tag. My guess would be a contraption from create. And as that is becoming more common of a thing I may need to add handling for excessively large packets to synchronize this data to client.

**Comment by P3pp3rF1y** [comment] 2024-09-18 21:52
in 1.21 neoforge large nbt is no longer an issue so closing as solved from that version on

**Closed as completed by P3pp3rF1y** 2024-09-18 21:52 UTC
Labels: enhancement
