### ISSUE TITLE
[1.17.1] Crash when trying to load with the CraftingTweaks mod.

### ISSUE THREAD

**Issue by Gbergz** [P3pp3rF1y/SophisticatedBackpacks#265] opened 2021-10-17 19:36 UTC
**Describe the bug**
The game crashes when trying to load with the [CraftingTweaks](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks) mod.

Loading with just Sophisticated Backpacks, CraftingTweaks + (Balm, dependency for CraftingTweaks.)
Game then crashes when the game is done loading.

**To Reproduce**
1. Have Sophisticated Backpacks, CraftingTweaks + (Balm, dependency for CraftingTweaks.) installed.
2. Launch Client.
3. Wait.
4. Crash.
5. See logs below.

**Expected behavior**
That the client boots up without crashing.

**Screenshots**
![image](https://user-images.githubusercontent.com/26634554/137642295-56c8ea38-dcd2-4a80-b014-c71cdfe7c897.png)

**Logs & Crash-Report**
**Logs:** https://gist.github.com/Gbergz/79fb411eb92dfd0e2c882a3e6f8efcf1
**Crash-Report:** https://gist.github.com/Gbergz/973bfd4842e8b312f1b8205afaea2447

**Versions**
**MC:** 1.17.1
**Forge:** 37.0.84
**Sophisticated Backpacks:** 1.17.1-3.5.2.37
**CraftingTweaks:** 13.0.0+0.
**Balm:** 1.6.0+0.

### EDIT
From CraftingTweaks github issue page:
`"Seems to be caused by outdated integration code on Sophisticated Backpack's side."`

**Comment by RepoDraghon** [comment] 2021-10-24 07:19
I have the same issue, thanks, now I know what mod it is that is causing this issue...

**Comment by RepoDraghon** [comment] 2021-10-24 08:23
Crafting Tweaks had this response. "Seems to be caused by outdated integration code on Sophisticated Backpack's side."

**Comment by P3pp3rF1y** [comment] 2021-11-01 19:50
fixed in the latest version on curseforge.

**Closed as completed by P3pp3rF1y** 2021-11-01 19:50 UTC
