### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by Klouver-github** [P3pp3rF1y/SophisticatedBackpacks#226] opened 2021-08-25 02:25 UTC
**Describe the bug**
anytime I open backpack it crashes the game cause of rendering or GUI 
https://paste.gg/p/anonymous/d80ba030e44a47dd83aeee21dd9d520d
**To Reproduce**
Steps to reproduce th
**Versions**
1.16.5

**Comment by P3pp3rF1y** [comment] 2021-08-25 05:58
You have a ton of mods there and many of which are core mods that change vanilla code and one of them is causing this issue as it crashes in the vanilla part of the code. 
I don't see how this could be caused by sbp and there's nothing in this crash that points to sbp code causing it.
To investigate more I will need you to limit the number of mods to the minimum set with which it still crashes or get me better crash log that points to an issue in sbp code.

**Comment by P3pp3rF1y** [comment] 2021-09-10 15:36
closing as no additional info was provided and the crash log doesn't mention sophisticated backpacks in the stack trace

**Closed as completed by P3pp3rF1y** 2021-09-10 15:36 UTC
Labels: Need Info
