### ISSUE TITLE
 items where gone 

### ISSUE THREAD

**Issue by manzipan** [P3pp3rF1y/SophisticatedBackpacks#33] opened 2021-02-03 10:29 UTC
hey there
me and a freind play on a server and i crafted a packpack after he crafted his he had all the items that i had in my backpack in his backpack aswell then i logged off and to my suprise when i loged on again all my items where gone. 
i use this mod on server with 1.16.5  how would i do the install properly ? sorry for my englisch im swiss

**Comment by P3pp3rF1y** [comment] 2021-02-03 12:38
This sounds like you're using the latest version and have duplicated the backpack in creative then it gets linked to the same storage behind the scenes. There's nothing I can do about that without doing heavy modifications to the base minecraft code and even then it wouldn't solve issues when other mods have inventory screens.

If that isn't the case I will need to know the version of the mod you're playing with and the steps to recreate as I am not aware of a way that would make this happen.

**Comment by manzipan** [comment] 2021-02-03 14:27
well i crafted the backpack through the crafting table with the right
materials and the freind did too i might have been in creative while
crafting it but i did use the crafting table  i was using forge 36.0.13 and
spohisticated paclpack mod ver 1.3.4.139 alpha i updated the mod to 142
now. is this a onetime issue or would i have to craft a new backpack to fix
it while not in creative ?

P3pp3rF1y <notifications@github.com> schrieb am Mi., 3. Feb. 2021, 13:39:

**Comment by P3pp3rF1y** [comment] 2021-02-03 17:14
alpha version of the mod? where did you download it from?

**Comment by P3pp3rF1y** [comment] 2021-02-03 17:18
And I still don't have explanation for that as changes made after don't seem to explain why this would be happening. But definitely if you use an alpha version of the mod it's not guaranteed to work correctly / not break your game or potentially lose your items that's an indev version. So if you want to prevent this please use versions that are released on curseforge.

I am going to leave this open for a bit in case you can figure out steps to recreate the issue with release version of the mod or someone else reports similar issue. But I will likely just close later on if there's no additional information.

**Comment by manzipan** [comment] 2021-02-03 17:50
is there a release for 1.16.5

P3pp3rF1y <notifications@github.com> schrieb am Mi., 3. Feb. 2021, 18:18:

**Comment by P3pp3rF1y** [comment] 2021-02-03 20:30
just check on curseforge there's one released yesterday and even at least a couple previous ones run on 1.16.5 no problem

**Comment by brisingraerowing** [comment] 2021-02-05 02:08
I'm seeing similar behavior with backpacks pulled from either the Creative inventory or JEI cheat mode, but the issue is intermittent. It may or may not happen with any particular cheated in backpack, and the backpack it seems to clone is random as well.

**Comment by P3pp3rF1y** [comment] 2021-02-05 21:32
yes that will happen as there's unfortunately no way I can detect that backpack is being cloned using one of these methods which should use a new storage vs just being copied which shouldn't get new storage. Both of these use the exact same copy method and I can't point the backpack to new storage every time it's copied as there is a number of scenarios in which copy doesn't mean new backpack - like every time a backpack is moved between slots there's a copy of it created and the same happens on client when a backpack is synced - so pointing to new storage would in better case mean desync between client and server and in worse case it would mean losing all items. 

But this only applies to getting the backpack in creative or cheating it in using JEI. There should be no issues when it's crafted legitimately.

**Comment by P3pp3rF1y** [comment] 2021-02-06 22:20
there was another report #37 of similar issue which leads me to believe there is some mod out there which allows modifying base recipe result which would mean the storage would get attached there and from that point on any crafting of backpack would result in backpack connected to the same storage. I can't recreate this with just SBP hence suspicion something out there is causing it. 
And I have just released a version that on crafting a backpack removes link to backpack storage from that stack. I believe this could solve your issue as well.

**Comment by manzipan** [comment] 2021-02-07 06:10
thanks it actualy was a onetime issue in my case. since then i never had
the problem again. i will dl the new ver. though and give it some testing.
and if u need the modlist running on server i could provide that... thanks
for the best backpack mod out there.

P3pp3rF1y <notifications@github.com> schrieb am Sa., 6. Feb. 2021, 23:20:

**Comment by P3pp3rF1y** [comment] 2021-02-07 23:26
I will just close this one then. In case you run into the issue again feel free to log a new issue with steps and the mod list

**Closed as completed by P3pp3rF1y** 2021-02-07 23:26 UTC
