### ISSUE TITLE
Mod Incompatibility

### ISSUE THREAD

**Issue by FooterManDev** [P3pp3rF1y/SophisticatedBackpacks#772] opened 2023-05-20 15:47 UTC
**Describe the bug**
When using Sophisticated Backpacks, loading into a world crashes the game, resulting in a Java error complaining about no memory. Disabling the mod prevents the bug.
This issue was found when using [Fun in the Sky.](https://github.com/TheGangModpacks/Fun-in-the-Sky) I am unable to reproduce with just Soph Backpacks and Soph Core, so I believe it to be a problem with another mod.
Crash log if it's a crash.
https://gist.github.com/FooterMan15/b7aa27d7f580e4e162d065343bf2f10e hs_err_pid
https://gist.github.com/FooterMan15/617719cbf842c7b037eb206b98bdda7a latest.log

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
Load the specified Modpack above ^
Attempt to load into a world. The game will crash after loading phase.

**Expected behavior**
No crash, I guess.

**Screenshots**
null 🤷 

**Versions**
3.18.45.819 - Backpacks
0.5.54.261 - Core
43.2.8 - Forge
A-0.1.2 - Modpack

**Comment by P3pp3rF1y** [comment] 2023-05-21 20:45
Sorry I have no idea why this is happening for you but I don't see anything in those logs that would connect the issue to SB and there are thousands of modpacks with the mod and definitely tens of thousands of players playing with it without issues. 
The only thing I can guess from the first log is that the issue is related to "The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap" because I definitely see that option enabled further down in the log. 
So you can try to mess with jvm options and fix it like that or figure out what mod combination is causing this. Anyway I don't think it's likely there is going to be anything to fix on SB side given in how many packs it's used and people definitely play with the mod with much less memory without any issues.
I am closing, but feel free to reopen if you find out that SB is actually the source of the issue here.

**Closed as completed by P3pp3rF1y** 2023-05-21 20:45 UTC
