### ISSUE TITLE
Random Items in the Upgrade-Slots

### ISSUE THREAD

**Issue by OwlNicole** [P3pp3rF1y/SophisticatedBackpacks#369] opened 2021-12-29 12:57 UTC
When I pick a backpack out of the creative menu on my server
There is a chance that some parts of my inventory (bar or straight up inventory) are sucked into the upgrade slots within the fresh backpack

If I do anything - close the backpack, attempt to get the items out of the upgrade slot or click - the game crashes.

**Comment by P3pp3rF1y** [comment] 2021-12-29 17:48
what version is it? is it in a modpack? can you recreate with just sbp? if not what mods are in the minimal set with which you can recreate?

The questions in the default template are there for a reason as without this info there's not much for me to do here other than close once I have retested pulling a backpack in creative and opening it, which I do several times every day so I am confident this doesn't happen with just sbp for me

**Comment by OwlNicole** [comment] 2021-12-30 12:06
I'm playing on a Forge 39.0.9 Minecraft 1.18.1 Server with a custom Modpack
with this mods here (and their Libs)
- FallingTree
- Alexs Mobs
- AntiMobGriefing
- Bioms O Plenty
- Automatic Doors
- Awesome Dungeons
- Clumps
- Comforts
- Cooking for Blockheads
- Corail Tombstone
- Croptopia
- Cursery
- Drawers Tooltips
- Flan
- Guard Villagers
- Habitat
- Iron Chests
- Jade
- JEI & JER
- Mr. Crayfish Furniture
- Oreberries Replanted
- Repurposed Structures
- Roots
- Schools of Magic
- Storage Drawers
- Taterzen
- Valhesia Core & Structures
- Waystones
- Xaeros Minimap & Map

- Sophisticated Backpacks (version sophisticatedbackpacks-1.18.1-3.14.3.485.jar via CurseForge)

- Item Sorter (got yeeted and replaced with Inventory Profiles Next in an attempt to "fix" the problem)

The error first occurred when the mod "Item Sorter" was added into the Modpack
Prior to that it never happend

When it first occurred I thought it was a lil glitch - this things happen. 
But it kept popping up every now and again
I kicked "Item Sorter" after I lost a two filled backpacks while trying to add the backpacks to the blacklist of that mod
After that I switched the "sorting" mod to "Inventory Profiles Next"
But the Error kept showing once or twice now, its a bit concerning
Maybe a fragment of the "Item Sorter" thingy but I don't know exactly

So I thought it would be good to let you know.
Maybe you can find reason for this weird glitch

**Comment by P3pp3rF1y** [comment] 2021-12-30 18:23
and are you sure that inventory profiles next isn't the cause of your issue here? - does it actually sort your backpack, if it does it's pretty likely that it's not going to be compatible with backpacks. You should really only be using backpack's built in sort functionality

**Comment by P3pp3rF1y** [comment] 2022-01-26 02:53
Any additional info on this?

**Comment by P3pp3rF1y** [comment] 2022-02-04 22:59
Closing as there was no follow up info provided

**Closed as completed by P3pp3rF1y** 2022-02-04 22:59 UTC
Labels: Need Info
