### ISSUE TITLE
Any stacks 128 items or above become invisible (stacking upgrade)

### ISSUE THREAD

**Issue by StormDragon-64** [P3pp3rF1y/SophisticatedBackpacks#553] opened 2022-07-28 17:38 UTC
**Describe the bug**
When using the stacking upgrade any stacks that contain 128 items or above become invisible, probably because the way minecraft handles stacks. Even though this is probably due to Minecraft's code, I am pretty sure that this is fixable, because there are other mods that have larger stacks and those are still visible.
**Mods**
I am using [my modpack](https://www.curseforge.com/minecraft/modpacks/create-mod-plus) along with optifine.

**To Reproduce**
1. Open backpack
2. Put multiple stacks of items in the backpack
3. Apply the stacking upgrade and sort the backpack to quickly stack the items together.
4. Stacks with more than 128 items are invisible but they are still there, and stacks with 127 items or less are still visible.

**Expected behavior**
Stacks with 128 items or higher would still be visible.

**Screenshots**
My screenshots aren't saving right now for some reason, I will send them later.

**Versions**
[sophisticatedbackpacks-1.18.2-3.18.4.646.jar](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/3887950)
Forge version: 40.1.57 (I can't use any version higher than this because optifine never updated to be compatible with any version higher than this.)
**Notes**
I am the creator of the modpack so I can change and update anything if I need to.
The stacks are still able to be interacted with even though they are invisible.

**Comment by Sshmoob** [comment] 2022-07-28 17:38
When I relogged the stacks became visible again, and I was unable to reproduce the error.

**Comment by Sshmoob** [comment] 2022-07-28 17:59
When I relogged back onto my server the stacks became visible again, and I was unable to reproduce the error.

**Comment by Sshmoob** [comment] 2022-07-28 22:45
When my friend crafted a stack upgrade and applied it for the first time the issue occurred for him as well, but when he relogged the issue stopped occurring for him as well.

**Comment by P3pp3rF1y** [comment] 2022-07-28 23:13
just update the mod, this is fixed in the latest release that happenede yesterday

**Closed as completed by P3pp3rF1y** 2022-07-28 23:13 UTC
