### ISSUE TITLE
1.20.1 advanced Refill Upgrade Bug

### ISSUE THREAD

**Issue by JaceValen** [P3pp3rF1y/SophisticatedBackpacks#918] opened 2023-11-29 18:44 UTC
**Describe the bug**
setting the backpack to refill Totems of undying into my offhand causes them to get deleted.

**To Reproduce**
1. put totems in backpack
2. put one in hand
3. set advanced refill to offhand
4. lose 74 totems in seconds

**Expected behavior**
I thought it would not delete my totems

**Versions**
Minecraft 1.20.1 on Forge

**Comment by P3pp3rF1y** [comment] 2023-11-29 20:28
I am unable to recreate with just sophisticated mods. It will fill one totem and only refills when that one is removed. So this is very likely caused by some conflict of mods in your modpack. If you can recreate with just sophisticated please provide steps how I can recreate.

**Comment by JaceValen** [comment] 2023-11-30 14:59
Upon more testing. it seems to be a conflict with two-handed weapons. I don’t think the backpack detects there being a totem in my hand when i’m holding a two-handed weapon, so if i have the refill set to offhand, it will drain the rest of my stash.

**Comment by P3pp3rF1y** [comment] 2023-11-30 16:23
Then it depends how that mod has implemented the two handed weapons. Sounds like it's doing some Shenanigans with removing stacks from offhand. I am closing this ticket as all SB does there is simply put stack in offhand slot which player has under normal circumstances so fix for this issue would need to be found on whatever the mod is that adds two handed weapons (I guess even if it means just dropping stacks that any other mod may be putting in player's offhand).

**Closed as completed by P3pp3rF1y** 2023-11-30 16:23 UTC
Labels: question
