### ISSUE TITLE
Seeing other players inventories????

### ISSUE THREAD

**Issue by Explode007** [P3pp3rF1y/SophisticatedBackpacks#37] opened 2021-02-06 20:09 UTC
When I crafted my backpack, i have the same as one of my friends.

**Comment by Explode007** [comment] 2021-02-06 20:15
So i tested it in a single player and yeah, when crafting backpacks they have shared inventories for some reason.

**Comment by P3pp3rF1y** [comment] 2021-02-06 22:11
So this seems to be some kind of mod conflict where the other mod somehow makes a change to vanilla crafting which allows to write link to the storage directly into the base recipe and then crafting from that recipe produces backpacks that can see the same thing.
The reason why I feel this is mod is because I have tested the crafting quite a bit before release and just now have tested extensively with just vanilla in pack and then in Enigmatica 6 modpack and I am unable to recreate this issue. 
However I am going to add a small change that will cleanup the link to storage once the backpack is crafted just to be sure.

**Comment by P3pp3rF1y** [comment] 2021-02-06 22:16
try https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/3195107

**Comment by P3pp3rF1y** [comment] 2021-02-09 06:14
This should be fixed with the latest release - seems to have been caused by interaction between JEI's recipe view and SBP inventory tooltip feature, but with the latest release that no longer causes linking backpacks to the same storage.

**Closed as completed by P3pp3rF1y** 2021-02-09 06:14 UTC
