### ISSUE TITLE
Nested upgrades effect main Backpack.

### ISSUE THREAD

**Issue by I2pRandom** [P3pp3rF1y/SophisticatedBackpacks#910] opened 2023-11-20 21:25 UTC
**Describe the bug**
When using Nested backpacks, if a void upgrade is placed within a nested backpack. It will infect void items in the main backpack instead of backpacks nested within the backpacks with the Void upgrade. 

**To Reproduce**
1) Add the Void Upgrade to the backpack nested inside of the main backpack
2) Set, filters and begin picking up objects.
3) The backpack with the void upgrade will now void items picked up by the main backpack

**Expected behavior**
The void upgrade only voids items inside of the nested backpack and sub-nested backpacks, instead of the Backpack the Nested backpack is within.

**Screenshots**

**Versions**
1.18.2-3.18.65.933
Forge 40.2.7 Minecraft 1.18.2

**Comment by P3pp3rF1y** [comment] 2023-11-24 08:10
I will need to know more about your setup to find out what/if there's wrong here. What upgrades you have in your backpack + how are they setup?

What I feel is happening here is that you have pickup or magnet in the main backpack putting items in the backpack, then inception upgrade is setup to first put these in subbackpacks and because your subbackpack with void is one of the first these items get voided in it.

**Comment by I2pRandom** [comment] 2023-12-01 09:59
In the main backpack i have the advanced magnet upgrade set to match contents, in the nested backpack i have a pickup upgrade set to match contents then the void upgrade. 
In the nested backpack i locked the slots with the item memory and began pickup up items, and had noticed while mining that my ore was disappearing in the main backpack. i had eventually disabled the void upgrade in the nested backpack which was for mob drops, and the ore stopped disappearing after the stack was full.

**Comment by P3pp3rF1y** [comment] 2023-12-01 19:59
Well in that case it was working as intended provided that you had inception upgrade set to work with subbackpacks first because in that case it should try to insert into that backpack you had there and if it had void upgrade with filter that accepted the ores that would delete them.

**Comment by P3pp3rF1y** [comment] 2024-02-03 23:46
closing this one as it was only configuration of upgrades

**Closed as completed by P3pp3rF1y** 2024-02-03 23:46 UTC
Labels: question
