### ISSUE TITLE
Can't alter upgrade slots in config

### ISSUE THREAD

**Issue by KDFireHero** [P3pp3rF1y/SophisticatedBackpacks#979] opened 2024-02-16 17:41 UTC
I wanted to change the upgrade slots on netherite to 8 and did /reload, still stuck with three restarted the game still three, I've double and triple checked to make sure the config file is saved with my edits

I am using the "Steampunk [LPS]" modpack on CurseForge on pack version: v21.5.zip
it uses the sophisticated core version: 1.19.2-0.5.111.525.jar
along with sophisticated backpacks version: 1.19.2-3.19.5.989.jar

**Comment by P3pp3rF1y** [comment] 2024-02-17 09:36
have you tried crafting a new backpack / getting a new one from creative screen?

**Comment by CryorusTheDragon** [comment] 2024-02-24 12:34
> I wanted to change the upgrade slots on netherite to 8 and did /reload, still stuck with three restarted the game still three, I've double and triple checked to make sure the config file is saved with my edits
> 
> I am using the "Steampunk [LPS]" modpack on CurseForge on pack version: v21.5.zip it uses the sophisticated core version: 1.19.2-0.5.111.525.jar along with sophisticated backpacks version: 1.19.2-3.19.5.989.jar

Had the same issue and tried troubleshooting for a good hour with this and found the solution.
At first I thought I was going mad but by chance I looked into the defaultconfigs folder in the modpack folder. 

This folder contains the configs that are loaded into a worlds "serverconfig" files on creation. 
By design even in singleplayer you play a solo local multiplayer world and the config files in that worlds config folder overwrite the global modpack "config" files. 
So you need to change those as well PER WORLD or just delete the contents of the default config folder for future worlds. 
The Default configs are only relevant for server hosting...

Sophisticated is working just fine. Just the modpack creator did something odd there by copying all of the base config files into the default files causing almost every global config to be overwritten per world. Never seen a modpack do them to THAT extent.

**Comment by P3pp3rF1y** [comment] 2024-09-18 20:03
closing given the feedback

**Closed as completed by P3pp3rF1y** 2024-09-18 20:03 UTC
Labels: question
