### ISSUE TITLE
Stuff disappears when put in bag...

### ISSUE THREAD

**Issue by therealeric** [P3pp3rF1y/SophisticatedBackpacks#158] opened 2021-05-29 08:09 UTC
**Describe the bug**
Using Netherite Bag with Stack Upgrade Tier 2

I place 10 sticks in my bag...   ...they disappear, never to be seen again...

SophisticatedBackpacks 2.4.0.259
Forge 36.1.24
Minecraft 1.16.5
Windows 7 Pro

What did I break???

**Comment by P3pp3rF1y** [comment] 2021-05-29 10:47
I have no idea and won't be able to help you with this as this exact thing seems to work for a lot of people including me. I will need more steps how exactly I can recreate this.

**Comment by therealeric** [comment] 2021-05-29 12:11
I, personally, think being able recreate this is going to be a little tough.  I think the biggest issue going here is the strange pack of mods I am using.

I put them together on a bit of weird idea I had.

We can pursue this if you want but the only way I can think of for you to do this is getting a hold a copy of the pack of mods I'm using.  I really don't think trying to type descriptions and explanations back and forth are going to help you in your search.  Just to give a bit of an idea what I am talking about, I'm using 192 mods... 

So, you will have to let me know what you want to do.

**Comment by P3pp3rF1y** [comment] 2021-06-02 20:15
I don't really have time to test everyone's pack when bugs happen. Or I could just do that instead of actually adding anything new to the mod and you can trust me I wouldn't enjoy that. This issue seems to be caused by the fact that there are two backpacks with the same UUID and I have a fix going out soon for something that was creating UUIDs on client unnecessarily even in recipe results. My guess is that one of your mods actually somehow syncs this to server and propagates that UUID to the recipe itself which then creates backpacks with the same UUID. I wasn't able to recreate this in two big packs I played recently but other people had similar issue with custom packs and suggested they can actually see the recipe result with the same uuid.
So once next version is out I am going to close this ticket and if you have any additional similar issues there should be a new ticket created for those with more info on how I can recreate.

**Comment by therealeric** [comment] 2021-06-02 20:31
<I don't really have time to test everyone's pack when bugs happen. Or I could just do that instead of actually adding anything new to the mod and you can trust me I wouldn't enjoy that.>

I agree with you completely...

If you aren't enjoying it, what's the point...

Thank you very much for your time
Eric

**Closed as completed** 2021-06-02 20:31 UTC
Labels: Fixed in dev
