### ISSUE TITLE
在游戏挂机过程中它崩溃了

### ISSUE THREAD

**Issue by LuckyDog322** [P3pp3rF1y/SophisticatedBackpacks#883] opened 2023-10-22 08:02 UTC
[crash-2023-10-22_15.43.31-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13062686/crash-2023-10-22_15.43.31-client.txt)
version:1.20.1

**Comment by P3pp3rF1y** [comment] 2023-10-22 08:36
I will need more info here - does this happen immediately as you open your inventory or there are some steps that need to happen.
This is likely caused by one of the many mods in your modpack there that does player rendering in addition to the regular vanilla rendering.

And please in English even if you're just using translator for that.

**Comment by P3pp3rF1y** [comment] 2024-09-18 21:15
closing given no follow up

**Closed as completed by P3pp3rF1y** 2024-09-18 21:15 UTC
Labels: Need Info
