### ISSUE TITLE
Double item bug

### ISSUE THREAD

**Issue by McAZero** [P3pp3rF1y/SophisticatedBackpacks#584] opened 2022-08-27 13:02 UTC
**Describe the bug**
Crash log if it's a crash.
Info on what other mods you're using that may cause a conflict here if applicable.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. open backpack and put items in from player A
2. use the switch-off-hand key on the backpack, open the GUI using the mouse,  and use the switch-off-hand key again without closing the inventory
3. throw the backpack to another player without closing the inventory still
4. player B opens backpack and both players A and B can now take out item duplicates

**Expected behavior**
Press f to switch the assistant, and then switch back to the item column to obtain double items.
Sorry, my English is not very good.(Video presentation only ↓↓↓

**Screenshots**
https://www.bilibili.com/video/BV11U4y167hE?share_source=copy_web&vd_source=e4a18c31c4f4bb1a481e9136cef95ded

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
sophisticatedbackpacks-1.16.5-3.15.16.669

**Comment by P3pp3rF1y** [comment] 2022-08-27 15:12
Looks like this is caused by a bug where dropping item from offhand wasn't handled in 1.16.5. This is fixed in 1.18 and on. As this is pretty critical one I will likely fix it even though I don't really do any additions to 1.16 anymore.

**Comment by P3pp3rF1y** [comment] 2022-08-30 12:33
Actually I will need info from you on how you're switching that backpack from your offhand to the hotbar - I am unable to recreate that and this is the cause of the bug here so I need to understand how that is done to even be able to test potential fix

**Comment by McAZero** [comment] 2022-08-30 18:43
![EU1B@`1UZ6H$K{T`$IBDOA0](https://user-images.githubusercontent.com/52328924/187517532-a8c9788a-1194-4f90-ae50-c8ee1e94c9ee.png)
My key is F
Move the mouse to the position where the backpack is to be placed

After switching, open the backpack and throw it to player B

**Comment by P3pp3rF1y** [comment] 2022-08-31 04:54
this is fixed in the latest release on curseforge

**Closed as completed by P3pp3rF1y** 2022-08-31 04:54 UTC
Labels: Need Info
