### ISSUE TITLE
Crash dedicated server on launch with Chipped, NoClassDefFoundError

### ISSUE THREAD

**Issue by gardenappl** [P3pp3rF1y/SophisticatedBackpacks#915] opened 2023-11-26 18:55 UTC
See https://github.com/P3pp3rF1y/SophisticatedStorage/issues/310, it's the same error. This occurs when I use REI on the server, or if I use no recipe viewer mod at all.

```
[26Nov2023 12:48:37.480] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: sophisticatedbackpacks, class net.p3pp3rf1y.sophisticatedbackpacks.SophisticatedBackpacks
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.3.jar%23113!/:?]
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.3.jar%23112!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: mezz/jei/api/registration/IRecipeCatalystRegistration
        at net.p3pp3rf1y.sophisticatedbackpacks.compat.chipped.ChippedCompat.init(ChippedCompat.java:49) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at net.p3pp3rf1y.sophisticatedbackpacks.init.ModCompat.initCompats(ModCompat.java:43) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
        at net.p3pp3rf1y.sophisticatedbackpacks.SophisticatedBackpacks.<init>(SophisticatedBackpacks.java:44) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: mezz.jei.api.registration.IRecipeCatalystRegistration
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.p3pp3rf1y.sophisticatedbackpacks.compat.chipped.ChippedCompat.init(ChippedCompat.java:49) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at net.p3pp3rf1y.sophisticatedbackpacks.init.ModCompat.initCompats(ModCompat.java:43) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
        at net.p3pp3rf1y.sophisticatedbackpacks.SophisticatedBackpacks.<init>(SophisticatedBackpacks.java:44) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
        ... 14 more
```

**Comment by Octelly** [comment] 2023-11-27 14:04
I am also having this issue
Here's a perma-link to the modpack I'm playing in its current state for reproducing the issue: https://github.com/OwO-Digital/silly_sandbox_1.18/tree/b7b94862040c312be2af377fb1c17f67eaa8a340

**Comment by Octelly** [comment] 2023-11-27 14:05
Also, the traceback makes it look like the crash happens because of missing JEI:

`Caused by: java.lang.ClassNotFoundException: mezz.jei.api.registration.IRecipeCatalystRegistration`

Some modpacks use REI or other alternatives though (such as the on I'm playing)

**Comment by Octelly** [comment] 2023-11-27 14:14
(sorry for the spam)

Just for completeness' sake, here's the `docker-compose` file I use:

```yml
version: "3.8"
services:
  mc:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      FORGE_VERSION: "40.2.14"
      VERSION: "1.18.2"
      PACKWIZ_URL: "https://1.18.silly-sandbox.packwiz.owo.digital/pack.toml"

      MEMORY: 6G
      VIEW_DISTANCE: 8
      SIMULATION_DISTANCE: 6
      MAX_PLAYERS: 2
      SYNC_CHUNK_WRITES: "FALSE"
      USE_AIKAR_FLAGS: true

      DIFFICULTY: "easy"
      ALLOW_FLIGHT: "TRUE"
      PVP: false
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
    restart: unless-stopped
```

**Comment by SuperChet** [comment] 2023-11-28 06:54
> See [P3pp3rF1y/SophisticatedStorage#310](https://github.com/P3pp3rF1y/SophisticatedStorage/issues/310), it's the same error. This occurs when I use REI on the server, or if I use no recipe viewer mod at all.
> 
> ```
> [26Nov2023 12:48:37.480] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: sophisticatedbackpacks, class net.p3pp3rf1y.sophisticatedbackpacks.SophisticatedBackpacks
> java.lang.reflect.InvocationTargetException: null
>         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
>         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
>         at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
>         at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
>         at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.3.jar%23113!/:?]
>         at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.3.jar%23112!/:?]
>         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
>         at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
>         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
>         at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
>         at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
>         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
>         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
> Caused by: java.lang.NoClassDefFoundError: mezz/jei/api/registration/IRecipeCatalystRegistration
>         at net.p3pp3rf1y.sophisticatedbackpacks.compat.chipped.ChippedCompat.init(ChippedCompat.java:49) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
>         at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
>         at net.p3pp3rf1y.sophisticatedbackpacks.init.ModCompat.initCompats(ModCompat.java:43) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
>         at net.p3pp3rf1y.sophisticatedbackpacks.SophisticatedBackpacks.<init>(SophisticatedBackpacks.java:44) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
>         ... 14 more
> Caused by: java.lang.ClassNotFoundException: mezz.jei.api.registration.IRecipeCatalystRegistration
>         at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
>         at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
>         at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
>         at net.p3pp3rf1y.sophisticatedbackpacks.compat.chipped.ChippedCompat.init(ChippedCompat.java:49) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
>         at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
>         at net.p3pp3rf1y.sophisticatedbackpacks.init.ModCompat.initCompats(ModCompat.java:43) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
>         at net.p3pp3rf1y.sophisticatedbackpacks.SophisticatedBackpacks.<init>(SophisticatedBackpacks.java:44) ~[sophisticatedbackpacks-1.20.1-3.18.68.952.jar%23107!/:1.20.1-3.18.68.952]
>         ... 14 more
> ```

Yep same, crashing 
[SophBP Crash.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13484569/SophBP.Crash.txt)

**Comment by P3pp3rF1y** [comment] 2023-11-30 16:44
this is fixed in the latest release on CF

**Closed as completed by P3pp3rF1y** 2023-11-30 16:44 UTC
