### ISSUE TITLE
Sometimes crashes when placing the backpack down

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [P3pp3rF1y/SophisticatedBackpacks#1019] opened 2024-03-29 11:41 UTC
**Describe the bug**
Sometimes, when placing down a backpack by pressing Sneak+RMB on a block, the game crashes (thrown into a "Saving world" screen and the game freezes, game gets saved). After loading the world again, the backpack is placed down on the ground and can be opened, inventory intact.

**To Reproduce**
1. Select the backpack on the hotbar
2. Sneak and right-click on the ground to place the backpack

**Expected behavior**
No crash

**Screenshots**
No screenshots

**Versions**
Game version: 1.18.2, mod version: 3.18.60.906, installed as part of CABIN modpack using curseforge client. Forge 40.2.18
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14803698/latest.log)

**Comment by JohnTheCoolingFan** [comment] 2024-03-29 11:43
[crash-2024-03-29_14.33.08-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14803717/crash-2024-03-29_14.33.08-client.txt)

**Comment by P3pp3rF1y** [comment] 2024-03-30 07:53
Some mod is causing code that is supposed to run before interation blocks are checked to not run. The only guess I have is rei plugin compatibilities because it for some reason seems to modify my code or at the very least it does some class loading on my code which is likely the cause of this issue. Try removing that and see if the issue persists but placing down backpack is extremely common thing that players do and I would have a ton of issues logged for that if it wasn't working so it's something to do with one of the mods in your modpack.

**Comment by P3pp3rF1y** [comment] 2024-09-17 18:42
closing given no additional info was provided

**Closed as completed by P3pp3rF1y** 2024-09-17 18:42 UTC
Labels: question
