### ISSUE TITLE
Opening backpack gives error

### ISSUE THREAD

**Issue by husky2331** [P3pp3rF1y/SophisticatedBackpacks#679] opened 2023-01-12 01:27 UTC
**Describe the bug**
After playing on my server which has the All The Mods 8 1.0.8 modpack installed for a couple of hours I tried to open my backpack but I couldn't. Opening the console revealed that every time I try to open that specific backpack gives an error. I have managed to import probably everything from the backpack to my storage system.

https://pastebin.com/4qi1gekM

**To Reproduce**

Unable to reproduce as I have no idea what caused it.

**Expected behavior**
The backpack should normally open.

**Screenshots**
N/A

**Version**
sophisticatedcore-1.19.2-0.5.37.198
sophisticatedbackpacks-1.19.2-3.18.40.775

**Comment by P3pp3rF1y** [comment] 2023-01-13 09:46
This is due to error in Immersive Engineering recipe that they have resolved in dev, but haven't released a new version with that fix yet.

The implementation of crafting upgrade has been this way for a very long time relying on the fact that all recipes are not going to break, but I will likely include a bit of code that will prevent exception like these caused by other mods' recipes from breaking opening the backpack.

**Comment by P3pp3rF1y** [comment] 2023-03-28 09:40
closing, the original issue is resolved on IE side and I have another issue open for exception handling addition so that future issues with broken recipes like this don't cause crashes.

**Closed as completed by P3pp3rF1y** 2023-03-28 09:40 UTC
