### ISSUE TITLE
Crash with anvil upgrade. (Mod Conflict (Apotheosis?))

### ISSUE THREAD

**Issue by HeavyDeception** [P3pp3rF1y/SophisticatedBackpacks#950] opened 2024-01-15 01:14 UTC
**Describe the bug**
Was combining 2 diamond helms in the anvil upgrade (They had apotheoses Aff on them.)
I was able to put them both in it looked to see how much EXP I need to combine them and close the backpack.
After that I couldn't open it.
Restarted the world, and I was able to open the backpack, but the anvil was closed.
Tried uninstalling it and reinstalling it and it crashed.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack add anvil upgrade
2. add 2 helms with Affx on them
3. close backpack
4. try to open

**Expected behavior**
opens bag and I can use the anvil

**Screenshots**
Crashes if I try to open the anvil just looks like a normal backpack.

**Log**
https://mclo.gs/ozLBupc

**Versions**
ModPack :ATM9 0.2.36

Soph Backpack: 3.19.5
Soph Core: 05.113.524
Apotheosis: 7.2.1

**Comment by P3pp3rF1y** [comment] 2024-01-15 16:38
Could you share the crash log for that crash as well?

**Comment by HeavyDeception** [comment] 2024-01-20 19:46
Was the Mclo link not the log for it?
https://pastebin.com/y2bSMgrn

Try this? Sorry about that wait.

**Comment by HeavyDeception** [comment] 2024-01-20 19:48
https://mclo.gs/rdclQ8m Mouse wheel

https://mclo.gs/Od3jwj4  Rendering overlay

These may be it.

**Comment by P3pp3rF1y** [comment] 2024-01-21 13:17
> Was the Mclo link not the log for it? https://pastebin.com/y2bSMgrn
> 
> Try this? Sorry about that wait.

Ahh right sorry somehow skipped over that link. That one was definitely enough. I can see where the issue is and will fix that for the next release.

**Comment by P3pp3rF1y** [comment] 2024-03-13 19:56
This was fixed with one of the last few releases I just haven't closed the issue

**Closed as completed by P3pp3rF1y** 2024-03-13 19:56 UTC
Labels: bug, Fixed in dev
