### ISSUE TITLE
Unable to open a specific backpack

### ISSUE THREAD

**Issue by Lunch-Breakfast-Dinner** [P3pp3rF1y/SophisticatedBackpacks#681] opened 2023-01-13 02:00 UTC
**Describe the bug**
Randomly unable to open one specific backpack. No crash, Tried to use a back up, Still can't open specific backpack.

**Versions**
sophisticatedbackpacks-1.19.2-3.18.40.775
within All the Mods 9-1.0.7 (current release at time of bug)

**Comment by P3pp3rF1y** [comment] 2023-01-13 09:20
Could you check debug.log at the time that you're trying to open the backpack if it has anything in it? Otherwise I don't have anything to use here to recreate really.

**Comment by bobbygithub1** [comment] 2023-01-14 00:59
I am having the same issue if you are able to take a look

3 players have been using the backpacks, only mine glitches. Two in a row have glitched. I am unable to open the backpack inventory or GUI but items can be pumped in and out of it with pipes. 

[latest (2).log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10416308/latest.2.log)

**Comment by bobbygithub1** [comment] 2023-01-14 03:03
May be related to industrial foregoing or mekanism items being placed in the backpack

**Comment by bobbygithub1** [comment] 2023-01-14 03:08
> [P3pp3rF1y](https://github.com/P3pp3rF1y) commented [17 hours ago](https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/679#issuecomment-1381553093)
This is due to error in Immersive Engineering recipe that they have resolved in dev, but haven't released a new version with that fix yet. The implementation of crafting upgrade has been this way for a very long time relying on the fact that all recipes are not going to break, but I will likely include a bit of code that will prevent exception like these caused by other mods' recipes from breaking opening the backpack.

**Comment by bobbygithub1** [comment] 2023-01-14 03:12
![image](https://user-images.githubusercontent.com/122654118/212448203-988bb961-9807-4157-a118-e713e76e8107.png)

Yet a third shameful backpack extraction

**Comment by Lunch-Breakfast-Dinner** [comment] 2023-01-14 16:38
I recently experienced a ticking player crash loop from picking up or "Q'ing" out (I can't remember... took a break from having to restore from backups) an Immersive Engineering item using backpack and magnet as well. I believe it is a Pity Machine Frame sitting in front of me on the ground when the game crashes.

[crash-2023-01-14_08.30.28-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10418200/crash-2023-01-14_08.30.28-server.txt)

**Comment by P3pp3rF1y** [comment] 2023-01-14 19:29
yes that all is the exact same exception - crafting upgrade trying to find out recipe for IF item that has custom rarity which crashes IE recipe that doesn't expect any custom rarities to exist despite the fact that custom rarities are natively supported by forge

**Comment by Mitchell5200** [comment] 2023-01-19 10:10
Looks like IE has this fixed in dev, estimated release date of that update unknown though

**Comment by P3pp3rF1y** [comment] 2023-01-20 11:02
Yeah, I will try to get a change out that will only log these errors and try to ignore, just from the top of my head I am not sure if that will still break some recipes - if the whole recipe evaluation is stopped if one of them breaks like this and thus the crafting upgrade may not show any recipe, but that's likely solvable given that at least vanilla crafting table seems to work

**Comment by superdusto** [comment] 2023-02-01 21:49
I am having this issue as well. Anyone find a good workaround? I need to get my other expensive upgrades out of the backpack.

**Comment by P3pp3rF1y** [comment] 2023-02-06 17:31
@superdusto immersive engineering has a new release out so just update to that version and you should be good. I will leave this open for the addition of exception handling in the crafting upgrade which I am going to add in the near future

**Comment by P3pp3rF1y** [comment] 2023-03-28 07:09
Just added exception handling for broken recipes in dev so this will be included in the next release

**Comment by P3pp3rF1y** [comment] 2023-03-30 17:19
Just released version with exception handling on curseforge

**Closed as completed by P3pp3rF1y** 2023-03-30 17:19 UTC
Labels: Implemented in Dev
